version: '2'

services:
    nginx:
        image: nginx:1.13.9
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html
            - ./docker/php/config.ini:/usr/local/etc/php/conf.d/uploads.ini
        links:
            - mysql

    mysql:
        image: mysql:5.7.17
        ports:
            - 3306:3306
        volumes:
            - ~/.backup/mysql/documents:/var/lib/mysql
            - ./docker/mysql/mysql-custom.cnf:/etc/my.cnf
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_ROOT_USER=root"
            - "MYSQL_DATABASE=documents"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8001:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql